import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from "../components/Navbar";
import pic from "../public/home.gif";
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {data:isAuthenticated} = useSession();
  const router = useRouter();
  useEffect(()=>{
      if(!isAuthenticated){
          router.push('/login')
      }
  }, [isAuthenticated, router])
  return (
 <>
 <Head>
   <title>Create Next App</title>
   <meta name="description" content="Generated by create next app" />
   <meta name="viewport" content="width=device-width, initial-scale=1" />
   <link rel="icon" href="/favicon.ico" />
 </Head>
{ isAuthenticated &&   
 <main className="w-full flex flex-col justify-center items-center">
   <Navbar/>
<span className='lg:text-5xl text-2xl text-gray-700 font-bold my-16 font-raleway'> Welcome to Home Page</span>
<Image src={pic} alt="" className='' width={600} height={600}/>
 </main>}
</>
  )
}